on:
  pull_request:
    branches:
      - main
jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Install depedencies
        run: yarn
      - name: Build hoggar
        run: yarn build:hoggar
      - name: Build icosium
        run: yarn build:icosium
