on:
  pull_request:
    branches:
      - main
    paths:
      - "hoggar/**"
      - "icosium/**"
jobs:
  change-scope-filter:
    runs-on: ubuntu-latest
    outputs:
      hoggar: ${{ steps.filter.outputs.hoggar }}
      icosium: ${{ steps.filter.outputs.icosium }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hoggar:
              - 'hoggar/**'
              - '.github/workflows'
            icosium:
              - 'hoggar/**'
              - '.github/workflows'
  ci-hoggar:
    runs-on: ubuntu-latest
    needs: change-scope-filter
    if: needs.change-scope-filter.outputs.hoggar == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install depedencies
        run: yarn
      - name: Lint
        run: yarn hoggar:lint
      - name: Setup db
        run: yarn hoggar:generate && yarn hoggar:migrate
        env:
          DATABASE_URL: file:data/db.sqlite
      - name: Test
        run: yarn hoggar:test
  ci-icosium:
    runs-on: ubuntu-latest
    needs: change-scope-filter
    if: needs.change-scope-filter.outputs.icosium == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install depedencies
        run: yarn
      - name: Lint
        run: yarn icosium:lint
      - name: Test
        run: yarn icosium:test
