on:
  pull_request:
    branches:
      - main
    paths:
      - "hoggar/**"
      - "icosium/**"
jobs:
  change-scope-filter:
    runs-on: ubuntu-latest
    outputs:
      hoggar: ${{ steps.filter.outputs.hoggar }}
      icosium: ${{ steps.filter.outputs.icosium }}
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            hoggar:
              - 'hoggar/**'
              - '.github/workflows/**'
            icosium:
              - 'icosium/**'
              - '.github/workflows/**'
  ci-hoggar:
    runs-on: ubuntu-latest
    needs: change-scope-filter
    if: needs.change-scope-filter.outputs.hoggar == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install depedencies
        run: yarn
      - name: Lint
        run: yarn hoggar:lint
      - name: Postgres - launch dockerized db
        run: cd hoggar && docker compose up -d
      - name: Prisma - Generate Client && Migrate
        run: yarn hoggar:generate && yarn hoggar:migrate
        env:
          DATABASE_URL: postgresql://postgres:postgress@localhost:5432/postgres
      - name: Test
        env:
          DATABASE_URL: postgresql://postgres:postgress@localhost:5432/postgres
        run: echo $DATABASE_URL && yarn hoggar:test
      - name: Postgres - stop dockerized db
        run: cd hoggar && docker compose down
  ci-icosium:
    runs-on: ubuntu-latest
    needs: change-scope-filter
    if: needs.change-scope-filter.outputs.icosium == 'true'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install depedencies
        run: yarn
      - name: Lint
        run: yarn icosium:lint
      - name: Test
        run: yarn icosium:test
